### PR TITLE
Fixed bug with quests not loading on Android

### PR DESCRIPTION
**Pull request by Onekone**
Replaced "program_directory" with "working_directory" so that GMS' file handler would look at the included files

### CODE REVIEW

**Comment by YalekW5435** [comment]
Didnt realize that Deeno released this for android.

**Comment by Onekone** [comment]
Well, because he didn't. I'm in a way volunteered to do it for him, since I have the exporter

**Comment by YalekW5435** [comment]
Whats really shocking is that **im** the only one who isnt ALLOWED to volunteer to do anything for this title, no asset adding, no music, etc.

**Comment by Onekone** [comment]
I'm sure that if you ask _nicely_  you can contribute to the game

**Comment by YalekW5435** [comment]
let me DM you the details on discord as to why Im literally:
1.  Not his friend, according to his eyes.
2.  Am not allowed to be a part of this project, according to him, regardless of asking nicely.

Yalek W.#5435 if you need my discord.

**Pull request merged**
